### ISSUE TITLE
有没有办法支持ipywidgets 可视化组件的展示

### ISSUE THREAD

**Issue by w-yuj** [Z-J-wang/render-juypter-notebook-vue#19]

**Comment by Z-J-wang** [comment]
render-juypter-notebook-vue 只实现了jupyterlab页面展示功能，其代码是全局基于JS的。ipywidgets是python插件，需要python运行环境，且属于编辑功能的插件。所以render-juypter-notebook-vue没法支持ipywidgets可视化组件。
